# Generated by Django 4.2.4 on 2023-09-26 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poesias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poesias.autor')),
                ('categoria', models.ManyToManyField(to='poesias.categoria')),
            ],
        ),
    ]
