# Generated by Django 4.2.4 on 2023-09-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poesias', '0003_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(default='PIX', max_length=100),
        ),
    ]
